### ISSUE TITLE
Got the error >>> Warning: <stdin>: syntax error in line 4 near '"'

### ISSUE THREAD

**Issue by ksridhar** [TomConlin/xpath2dot#3]
First of all, i thank you for this piece of code.

i got this error
```
Warning: <stdin>: syntax error in line 4 near '"'
``` 
while trying
```
xmlstarlet el -a RCV000077146.xml | sort -u | \
 xpath2dot.awk -v ORIENT="UD" | dot -T png > xpath2dot_demo_att.png
```

Got the version of awk through
```
$`readlink -e /usr/bin/awk` --version
GNU Awk 4.0.1
Copyright (C) 1989, 1991-2012 Free Software Foundation.
```

Found the problem to be the double-quote character (") inside label. i.e.
the expected dot line was 
```
"ID" [label = "{<ID> ID|Source}" shape = "record"];
```
instead of the (erroneous)
```
"ID" [label = "{<"ID"> "ID"|"Source"}" shape = "record"];

```

Read [this example](https://renenyffenegger.ch/notes/tools/Graphviz/elems/node/main-types/record-based) to arrive at the above decision

naively corrected this as follows in END
```
for(n in node){
    #{added
    bare_n = n
    gsub(/"/,"", bare_n)
    }
    attributes = ""
    for(a in node[n]){
        #{added
        bare_a = a
        gsub(/"/,"", bare_a)
        }
        #{replaced
        #attributes = attributes "|" a
        #with
        attributes = attributes "|" bare_a
        #}
    }
    #{replaced
    #print n " [label = \"{<" n "> " n "|" substr(attributes,2) "}\" shape = \"record\"];"
    #with
    print n " [label = \"{<" bare_n "> " bare_n "|" substr(attributes,2) "}\" shape = \"record\"];"
    #}
}
```

i have not edited the master nor created a branch as i leave you with the decision to be taken about this issue.

thank you once again

**Comment by TomConlin** [comment]
Hi @ksridhar 

First  I thank you for your perfectly executed report.

I am on a newer version of gawk... 

```
`readlink -e /usr/bin/awk` --version
GNU Awk 5.0.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.2.0)
Copyright (C) 1989, 1991-2019 Free Software Foundation.
```
but...
I also see an un-pushed diff  hanging out on my working dir that looks like it 
is about "not double quoting vars"  which I had because it allowed embedded spaces but apparently caused other problems.


```
git diff 
diff --git a/xpath2dot.awk b/xpath2dot.awk
index 25c6686..14c164d 100755
--- a/xpath2dot.awk
+++ b/xpath2dot.awk
@@ -18,9 +18,10 @@
 # but we are not enforcing inital char or length here
 # just replacing runs of non-alphanums with underscore
 # so they can be used as node labels in dot
+# quoting allows spaces in names but causes other problems
 function sanitize(var){
        gsub(/[ !"#$%&'()*+,\-./:;<=>?@[\\\]\^_`{|}~]+/, "_", var);
-       return "\"" var "\""
+       return var
 }
 
```

I will push this now and perhaps you can let me know if it addresses the behavior you see. 
 
Again thanks for the report

**Comment by ksridhar** [comment]
Thank you.
